#!/bin/bash

if [ ! -f .testEnvRunning ]
then
    echo -e "\x1b[31m\nPlease execute \x1b[1;3m./startTestEnv --wait \x1b[0m\x1b[31mand run this script again\x1b[0m\n"
    exit 1;
fi
cp ./temp/config.yaml .

classpath="./core/*:./plugin-interface/*:./ee/*"

if which cygpath > /dev/null; then # Convert path to Windows-style if using Git Bash
  classpath="$(cygpath -C ANSI -w -p "${classpath}")"
fi

java -classpath "${classpath}" io.supertokens.Main ./ DEV
