#!/bin/bash

function cleanup {
  if [[ $cicd = true ]]; then
    ./utils/cleanTestEnvCicd
  else
    ./utils/cleanTestEnvLocal
  fi
}

usage="Usage: startTestingEnv [--help] [--wait] [--silent] [--cicd] [--force]"
wait=false
silent=false
cicd=false
force=false

# Based on https://stackoverflow.com/a/33826763/11827673
while [[ "$#" -gt 0 ]]; do
  case $1 in
    -h|--help)   echo "$usage"; exit ;;
    -w|--wait)   wait=true   ;;
    -s|--silent) silent=true ;;
    -c|--cicd)   cicd=true   ;;
    -f|--force)  force=true  ;;
    *) echo "Unknown parameter passed: $1"; echo "$usage"; exit 1 ;;
  esac
  shift
done

if [[ $force = true && -f .testEnvRunning ]]; then
  [[ $silent = false ]] && echo "Removing previous testing environment..."
  cleanup
fi

trap cleanup EXIT

[[ $silent = false ]] && echo "Setting up testing environment..."
if [[ $cicd = true ]]; then
  ./utils/setupTestEnvCicd
else
  ./utils/setupTestEnvLocal
fi


if [[ $wait = true ]]; then
  [[ $silent = false ]] && echo "Test environment started! Leave this script running while running tests."
  # Wait for the user to end the session
  while true; do
    sleep 1
  done
else
  [[ $silent = false ]] && echo "Running all tests..."
  # Tests are run relative to the project's folder
  ./gradlew test
fi
