#!/bin/bash

function cleanup {
	if [[ $1 = "--cicd" ]]
	then
		./utils/cleanTestEnvCicd
	else
		./utils/cleanTestEnvLocal
	fi 
}

trap cleanup EXIT

wait=false

if [[ $1 = "--cicd" ]]
then
	if [[ $2 = "--wait" ]]
	then
		wait=true
	fi
	./utils/setupTestEnvCicd
else
	if [[ $1 = "--wait" ]]
	then
		wait=true
	fi
	./utils/setupTestEnvLocal	
fi


if [[ $wait = "true" ]]
then
  echo "Test environment started! Leave this script running while running tests."
	# we wait for user to end the session
	while [[ true ]]
	do
		echo "Test environment running..."
	    sleep 2
	done
else
  echo "Running all tests..."
	# ../ because the tests are run relative to the project's folder.
	./gradlew test
fi
