#!/bin/bash

usage="Usage: cleanTestEnv [--help] [ [--cicd] | [--local] ] [--silent]"
cicd=false
silent=false
tmp_path=".tmp/supertokens-core"

# Based on https://stackoverflow.com/a/33826763/11827673
while [[ "$#" -gt 0 ]]; do
  case $1 in
    -h|--help)   echo "$usage"; exit ;;
    -c|--cicd)   cicd=true   ;;
    -l|--local)  cicd=false  ;;
    -s|--silent) silent=true ;;
    *) echo "Unknown parameter passed: $1"; echo "$usage"; exit 1 ;;
  esac
  shift
done

rm -rf $tmp_path/core
rm -rf $tmp_path/plugin-interface
rm -rf $tmp_path/plugin
rm -rf $tmp_path/cli
rm -rf $tmp_path/downloader
rm -rf $tmp_path/ee
rm -rf $tmp_path/version.yaml
rm -rf $tmp_path/config.yaml
rm -rf $tmp_path/install
rm -rf $tmp_path/install.bat
rm -rf $tmp_path/LICENSE.md
rm -rf $tmp_path/.testEnvRunning

[[ $silent = false ]] && echo "Testing environment destroyed."