#!/bin/bash

usage="Usage: cleanTestEnv [--help] [ [--cicd] | [--local] ] [--silent]"
cicd=false
silent=false

# Based on https://stackoverflow.com/a/33826763/11827673
while [[ "$#" -gt 0 ]]; do
  case $1 in
    -h|--help)   echo "$usage"; exit ;;
    -c|--cicd)   cicd=true   ;;
    -l|--local)  cicd=false  ;;
    -s|--silent) silent=true ;;
    *) echo "Unknown parameter passed: $1"; echo "$usage"; exit 1 ;;
  esac
  shift
done

INSTALL_DIR="${INSTALL_DIR:-.}"

rm -rf "$INSTALL_DIR/core"
rm -rf "$INSTALL_DIR/plugin-interface"
rm -rf "$INSTALL_DIR/plugin"
rm -rf "$INSTALL_DIR/cli"
rm -rf "$INSTALL_DIR/downloader"
rm -rf "$INSTALL_DIR/ee"
rm "$INSTALL_DIR/version.yaml"
rm -rf "$INSTALL_DIR/temp"
rm "$INSTALL_DIR/install"
rm "$INSTALL_DIR/install.bat"
rm "$INSTALL_DIR/LICENSE.md"
rm "$INSTALL_DIR/.testEnvRunning"
rm -rf "$INSTALL_DIR"/.started*
rm -f "$INSTALL_DIR"/config*.yaml
[[ $silent = false ]] && echo "Testing environment destroyed."
