version: '3'
services:
  supertokens_mysql_db:
    image: mysql/mysql-server:latest
    container_name: mysql_supertokens
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_USER: root
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: supertokens
      MYSQL_ROOT_HOST: '%'
    deploy:
      resources:
        limits:
          cpus: "0.25"
          memory: 500M
  supertokens_postgres_db:
    image: postgres:12
    container_name: postgres_supertokens
    restart: always
    ports:
      - '5432:5432'
    environment:
      POSTGRES_PASSWORD: root
      POSTGRES_USER: root
      POSTGRES_DB: supertokens
    deploy:
      resources:
        limits:
          cpus: "0.25"
          memory: 500M
