#!/bin/bash

utils_path="./utils/core"
packages_path="./packages"

mkdir $packages_path > /dev/null 2>&1

# ignore changes to these two files
git update-index --skip-worktree $utils_path/modules.txt
git update-index --skip-worktree settings.gradle
git update-index --skip-worktree .idea/runConfigurations/CLI_Main.xml
git update-index --skip-worktree .idea/compiler.xml
git update-index --skip-worktree .idea/vcs.xml

prefix=`$utils_path/project-prefix`

url=https://bitbucket.org/vrai-labs
if [[ $1 = "--ssh" ]]
then
  url=git@bitbucket.org:vrai-labs
fi

if [ $prefix == "supertokens" ]; then
	url=https://github.com/
	if [[ $1 = "--ssh" ]]; then
		url=git@github.com:
	fi
fi

# clear settings.gradle
> settings.gradle

echo "include '$packages_path/supertokens-core:cli'" >> settings.gradle
echo "include '$packages_path/supertokens-core:downloader'" >> settings.gradle
echo "include '$packages_path/supertokens-core:ee'" >> settings.gradle

# add new line char at the end in case it's not there for looping
echo  >> $utils_path/modules.txt

# looping
cat $utils_path/modules.txt | while read line
do
	if [[ ! -z "$line" ]] && [[ $line != //* ]]
	then
		while IFS=',' read -ra ADDR; do
			counter=0
			user_name=supertokens
      		for i in "${ADDR[@]}"; do
				if [ $counter == 0 ];
				 then
					repo_name="$i"
				else
					if [ $counter == 1 ];
					 then
						branch="$i"
					else
						user_name="$i"
					fi
          		fi
          		counter=$(($counter+1))
      		done
 		done <<< "$line"
 		
 		# we now have $repo_name and $branch and $user_name if exists for that repo

 		if [[ $repo_name != "sqlite-plugin" ]]
 		then
      (cd $packages_path && git clone --branch $branch $url$user_name/$prefix-$repo_name.git)

      cp $utils_path/pre-commit $packages_path/$prefix-$repo_name/.git/hooks/

      cp $utils_path/addDevTag $packages_path/$prefix-$repo_name/addDevTag
      cp $utils_path/addReleaseTag $packages_path/$prefix-$repo_name/addReleaseTag

      echo "include '$packages_path/$prefix-$repo_name'" >> settings.gradle
    fi

  fi
done


# remove new line char from end for next use of this script
printf %s "$(< $utils_path/modules.txt)" > $utils_path/modules.txt